runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /_ah/api/discovery/v1/apis/greeting/v1/rest
  script: hosts.api

- url: /_ah/api/hosts/v1/.*
  script: hosts.api
  login: required
  auth_fail_action: unauthorized

# The endpoints handler must be mapped to /_ah/spi.
# Apps send requests to /_ah/api, but the endpoints service handles mapping
# those requests to /_ah/spi.
- url: /_ah/spi/.*
  script: hosts.api

- url: /.*
  script: web.app


skip_files:
- .*.gz
- .*.zip


libraries:
- name: pycrypto
  version: 2.6
- name: endpoints
  version: 1.0
